### PR TITLE
TER-85 Use new form of share/link command

### PR DESCRIPTION
**Pull request by jirkasemmler**
Jira: TER-85

update Share/Link handlers based on https://github.com/keboola/php-storage-driver-common/pull/18

### CODE REVIEW

**Comment by jirkasemmler** [comment]
davam na CR i Romana bo vi jake se udelaly upravy na Commandech

**Review by romanbracinik — APPROVED** [review]
za mna cajk

**Review by martinjunger — APPROVED** [review]
ok

**Comment by jirkasemmler** [comment]
rebase + fix xdebug

**Pull request merged**
